### ISSUE TITLE
个人建议

### ISSUE THREAD

**Issue by nighca** [doxiaodong/darlin-react#1]
有点晚了，还是建 issue 说吧。

1. 组件的类名都是 `CompFoo`，为啥不是直接 `Foo`
2. 多 store 的话直接用就好了，不用通过 `defaultProps` 挂到 `this.props` 上再用
3. 通过 props 传递数据/方法的话，直接传 store 太重了，会增加父子组件的耦合，传数据跟回调函数的话耦合会小一点
4. `app/views` 下也有 `components`，不太确定跟 `app/components` 的定位区别
5. 感觉可以不要 `app` 这一层，直接把 `app` 里边的东西拿出来跟 `assets` 平级，这样层级会少一点

以上，供参考~

**Comment by doxiaodong** [comment]
1. store 那个被误导了，https://github.com/mobxjs/mobx-react-typescript-boilerplate/blob/master/src/index.tsx.
2. `ComoFoo` 只是为了区分 `ViewFoo`

感谢星神

**Comment by nighca** [comment]
哈哈客气，你好晚呐
